name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale 설정
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscaled &
          sleep 5
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTH_KEY }}
      - name: Tailscale 연결 확인
        run: |
          sudo tailscale status
          sudo tailscale ping ${{ secrets.EC2_HOST }} || true
          sleep 15
      - name: SSH로 EC2 원격 접속하기
        uses: appleboy/ssh-action@v1.0.3
        env:
          APPLICATION_PROPERTIES: ${{ secrets.APPLICATION_PROPERTIES }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          envs: APPLICATION_PROPERTIES
          script_stop: true
          script: |
            cd /home/ubuntu/befoo-server
            rm -rf src/main/resources/application.yaml
            git reset --hard origin/main
            git pull origin main --rebase
            echo "$APPLICATION_PROPERTIES" > src/main/resources/application.yaml
            ./gradlew clean build -x test
            sudo fuser -k -n tcp 8080 || true
            nohup java -Duser.timezone=Asia/Seoul -jar build/libs/*SNAPSHOT.jar > ./output.log 2>&1 &